export const GET_TASK_LIST = 'GET_TASK_LIST';
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_FAILURE = 'GET_TASK_LIST_FAILURE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const MODAL_ADD_ACTION = 'MODAL_ADD_ACTION';
export const MODAL_DELETE_ACTION = 'MODAL_DELETE_ACTION';

export const ADD_TASK_LIST = 'ADD_TASK_LIST';
export const ADD_TASK_LIST_SUCCESS = 'ADD_TASK_LIST_SUCCESS';
export const ADD_TASK_LIST_FAILURE = 'ADD_TASK_LIST_FAILURE';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const DELETE_TASK_LIST = 'DELETE_TASK_LIST';
export const DELETE_TASK_LIST_SUCCESS = 'DELETE_TASK_LIST_SUCCESS';
export const DELETE_TASK_LIST_FAILURE = 'DELETE_TASK_LIST_FAILURE';

export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const DRAGGED_TASK = 'DRAGGED_TASK';
export const DRAGGED_TASK_SUCCESS = 'DRAGGED_TASK_SUCCESS';
export const DRAGGED_TASK_FAILURE = 'DRAGGED_TASK_FAILURE';
